package com.eduardo.ekki.ekkiTransfer.service.validation;

public enum TransferValidationStatus {
	
	APPROVED_HAS_FUNDS,
	APPROVED_NEEDS_PASSWORD,
	APPROVED_NEEDS_CREDICART_LOAM,
	APPROVED_OVERRIDE_RECENT_TRANSACTION,
	APPROVED_OVERRIDE_NEEDS_PASSWORD,
	NOT_APPROVED_INSUFICIENT_FUNDS,
	NOT_APPROVED_NEEDS_CREDITCARD;

}
